[build]
rustflags = [
    "-Zlocation-detail=none",
    "-Zfmt-debug=none",
   # "-Ctarget-cpu=mvp"
]

[unstable]
build-std = ["std", "panic_abort"]
build-std-features = ["optimize_for_size", "panic_immediate_abort"]