[build]
rustflags = [
    # required for DecompressionStream
    # https://docs.rs/web-sys/latest/web_sys/struct.DecompressionStream.html
    "--cfg=web_sys_unstable_apis",
    # size
    "-Zlocation-detail=none",
    "-Zfmt-debug=none",
   # "-Ctarget-cpu=mvp"
]
target = "wasm32-unknown-unknown"

[unstable]
build-std = ["std", "panic_abort"]
build-std-features = ["optimize_for_size", "panic_immediate_abort"]