name: PR Check

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        run: |
          rustup update nightly
          rustup default nightly
          rustup target add wasm32-unknown-unknown

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Run cargo check on app
        run: cargo check --target wasm32-unknown-unknown --no-default-features --features font_hack
